# Site settings
title: vCloud Tools
email: vcloud-tools@digital.cabinet-office.gov.uk
description: "A collection of tools for provisioning in vCloud Director"
baseurl: ""
url: "http://rubygems.org/gems/vcloud-tools"
username: vcloud-tools

# Build settings
markdown: redcarpet
permalink: pretty
