require 'vcloud/core/entity'
require 'vcloud/core/vm'
require 'vcloud/core/vapp'
require 'vcloud/core/vapp_template'
require 'vcloud/core/edge_gateway'
require 'vcloud/core/org_vdc_network'
require 'vcloud/core/vdc'
require 'vcloud/core/vm_orchestrator'
